### ISSUE TITLE
Use of Django ugettext_lazy breaks with Django 4+

### ISSUE THREAD

**Issue by chosak** [cfpb/wagtail-treemodeladmin#35]
This project uses Django's [`ugettext_lazy`](https://docs.djangoproject.com/en/2.2/ref/utils/#django.utils.translation.ugettext_lazy) method [in several places](https://github.com/cfpb/wagtail-treemodeladmin/search?q=ugettext_lazy). `ugettext_lazy` was [deprecated in Django 3.0](https://docs.djangoproject.com/en/4.1/releases/3.0/#id3) and [removed in Django 4.0](https://docs.djangoproject.com/en/4.1/releases/4.0/#features-removed-in-4-0).

This project doesn't specify a particular pinned range for Django [in its setup.py](https://github.com/cfpb/wagtail-treemodeladmin/blob/1d7bc3d578b44e921d5d64bbd24304b4b284f4b6/setup.py#L3-L5) (although [it does for testing](https://github.com/cfpb/wagtail-treemodeladmin/blob/1d7bc3d578b44e921d5d64bbd24304b4b284f4b6/tox.ini#L22-L23)). This causes a failure unless you pin Django < 4:

```
% pip install wagtail-treemodeladmin
% pip freeze | grep Django==
Django==4.0.8
% pip freeze | grep wagtail==
wagtail==2.16.3
% wagtail start myproject
% cd myproject
# Edit myproject/settings/base.py to add 'treemodeladmin' to INSTALLED_APPS
% ./manage.py migrate
...
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'
```

**Comment by willbarton** [comment]
Good catch, thanks! I've replaced ugettext in [df3a0a7](https://github.com/cfpb/wagtail-treemodeladmin/pull/34/commits/df3a0a729a75c88cd258f6c566943454fd00d3a8) in #34.
