### ISSUE TITLE
Wagtail 5.2 compatibility?

### ISSUE THREAD

**Issue by dustinblanchard** [cfpb/wagtail-treemodeladmin#39]
This package was previously working fine in our application with Wagtail 5.2, but the new version hard locks it to  <5.2. 

Are there currently any known issues with 5.2?

**Comment by willbarton** [comment]
[Release 1.9.0](https://github.com/cfpb/wagtail-treemodeladmin/releases/tag/1.9.0) should support Wagtail 5.2!
